import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { GeistPixelSquare, GeistPixelGrid, GeistPixelCircle, GeistPixelTriangle, GeistPixelLine } from 'geist/font/pixel';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
    lang="en"
    className={`
      ${GeistSans.variable}
      ${GeistMono.variable}
      ${GeistPixelSquare.variable}
      ${GeistPixelGrid.variable}
      ${GeistPixelCircle.variable}
      ${GeistPixelTriangle.variable}
      ${GeistPixelLine.variable}
    `}
  >
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
